### ISSUE TITLE
Brainstorm UI design; identify components and establish layout

### ISSUE THREAD

**Issue by ayovev** [ayovev/project-blue-is#4]
We need to brainstorm and collectively agree on a good UI/UX baseline to start working towards. Something as simple as an MVP for what each "page" would look like and how it would behave would give me enough to begin identifying what components we can reuse from front-end frameworks like Grommet, Ant, and Blueprint, as well as which components we'll have to build on our own. Regardless, I want to have an initial idea by Tuesday (10/9) or at the very least use our meeting time on that day to work through some ideas and sketch out an MVP. I'd like to use Grommet for most of our front-end layout and styling with some custom CSS that we can skin over it. This way we still get the clean, functional look and feel we want without having to reinvent the wheel and dedicate too much time to that in the beginning.

**Comment by ayovev** [comment]
Starting Modules / Resources:
- Grommet
- Recharts

**Comment by schnebly** [comment]
TODO: 10/16/18 meeting

**Comment by schnebly** [comment]
Do we still need this on the kanban board?

**Comment by ayovev** [comment]
No, closing
